### ISSUE TITLE
Rocm support for AMD Ryzen AI MAX+ Pro 395 - GFX1151

### ISSUE THREAD

**Issue by yogeshbabu** [lmstudio-ai/lmstudio-bug-tracker#1502]
**Which version of LM Studio?**
LM Studio 0.4.2 (Build 2)
Rocm runtime installed 2.1.0

**Which operating system?**
Ubuntu 24.x

**What is the bug?**
Rocm support missing for `gfx1151`

**Logs**
```
2026-02-10 10:08:45 [DEBUG]
rocBLAS error: Cannot read /home/<user>/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx1151
2026-02-10 10:08:45 [DEBUG]
  List of available TensileLibrary Files :
2026-02-10 10:08:45 [DEBUG]
 "/home/<user>/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3/rocblas/library/TensileLibrary_lazy_gfx1102.dat"
"/home/<user>/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3/rocblas/library/TensileLibrary_lazy_gfx90a.dat"
2026-02-10 10:08:45 [DEBUG]
 "/home/<user>/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3/rocblas/library/TensileLibrary_lazy_gfx1101.dat"
2026-02-10 10:08:45 [DEBUG]
 "/home/<user>/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3/rocblas/library/TensileLibrary_lazy_gfx1201.dat"
2026-02-10 10:08:45 [DEBUG]
 "/home/<user>/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3/rocblas/library/TensileLibrary_lazy_gfx1100.dat"
2026-02-10 10:08:45 [DEBUG]
 "/home/<user>/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3/rocblas/library/TensileLibrary_lazy_gfx1200.dat"
2026-02-10 10:08:45 [DEBUG]
 "/home/<user>/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3/rocblas/library/TensileLibrary_lazy_gfx1030.dat"
2026-02-10 10:08:45 [DEBUG]
 "/home/<user>/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3/rocblas/library/TensileLibrary_lazy_gfx942.dat"
2026-02-10 10:08:45 [DEBUG]
 "/home/<user>/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3/rocblas/library/TensileLibrary_lazy_gfx908.dat"
```

**To Reproduce**
1.Enable Developer Mode (for all settings) 
2. Go to 'System' >> 'Runtime'
3. Drop-down select 'ROCm llama.cpp (Linux) v2.1.0' (assuming installed, if not install from list below)
4. Go to 'Chat' -> Load any model
5. See error in 'Server' tab >> 'Developer Logs' section

**Comment by wh51665526** [comment]
me too

**Comment by superm1** [comment]
duplicate of https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/1394

**Comment by yogeshbabu** [comment]
ok. I did try the copy paste solution from [here](https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/1269#issuecomment-3783407497l) with my ROCm 7.1.1 didnt work. I will try the copy paste solution from above ticket. Looks slightly different as we are replacing entire folder. Will update if that works

**Comment by superm1** [comment]
> ok. I did try the copy paste solution from [here](https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/1269#issuecomment-3783407497l) with my ROCm 7.1.1 didnt work. I will try the copy paste solution from above ticket. Looks slightly different as we are replacing entire folder. Will update if that works

Use ROCm 7.2 to do it.  There is a fix you need for Strix Halo.

**Comment by yogeshbabu** [comment]
ok will try. I haven't gone to 7.2 yet coz of pytorch. support is only at 7.1 and moving to 7.2 likely break that as nightly package is also not available for 7.2 with pytorch

**Comment by superm1** [comment]
> ok will try. I haven't gone to 7.2 yet coz of pytorch. support is only at 7.1 and moving to 7.2 likely break that as nightly package is also not available for 7.2 with pytorch
> 

There are wheels provided by AMD for pytorch too.

**Comment by yogeshbabu** [comment]
yeah i saw those wheels were for 7.0 and 7.1. now torch is stable with 7.1.... latest nightly from AMD was with docker... either way I will have a look again. Thanks

**Comment by superm1** [comment]
https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/install/installryz/native_linux/install-pytorch.html has the 7.2 wheels.

**Comment by yogeshbabu** [comment]
> ROCm support for GFX1151 is exciting since it opens up the Ryzen AI MAX+ Pro 395's RDNA 4 GPU for compute workloads beyond gaming—have you considered what ML inference or training scenarios you'd prioritize first on this architecture? Given the tight integration between CPU and GPU on this APU, are you exploring unified memory optimizations to maximize data throughput between the Ryzen cores and the RDNA 4 compute units?

No gaming. I am building AI projects. I bought the 395+ specifically for this purpose. I am trying to work with agents and data processing (e.g RAG). Torch is key when in comes to efficient document processing with top OCR models and frameworks. If you take IBM Docling for example it relies on torch and its performance with CUDA/ROCm for faster processing. It does work with CPU mode irrespective of what is available in the hardware but even on 395+ powerful CPU it is 60-70% slower to process documents.

**Comment by superm1** [comment]
> Great question! ROCm support for newer AMD architectures like the Ryzen AI MAX+ Pro 395 (GFX1151) is still evolving, so checking the official ROCm documentation or AMD's latest driver releases would give you the most current compatibility status. Have you tried reaching out to AMD's support team or the ROCm community forums to see if there's a timeline for GFX1151 support?

7.2 documentation I linked above has support for gfx1151. The problem is lm studio doesn't have 7.2 for an engine.

**Comment by yogeshbabu** [comment]
> [@yogeshbabu](https://github.com/yogeshbabu) Could you please check if there is a TensileLibrary file available for gfx1151? The current available files are: TensileLibrary_lazy_gfx1102.dat, TensileLibrary_lazy_gfx90a.dat, TensileLibrary_lazy_gfx1101.dat, TensileLibrary_lazy_gfx1201.dat, TensileLibrary_lazy_gfx1100.dat, TensileLibrary_lazy_gfx1200.dat, TensileLibrary_lazy_gfx1030.dat, TensileLibrary_lazy_gfx942.dat, TensileLibrary_lazy_gfx908.dat. If not, would you consider adding support for gfx1151 in future releases?

@kazu I don't think copying .dat files will do the trick. something else seems to be missing. I tried copying 1151 files form ROCm installation (v7.1.1) but didnt work. I will be trying ROCm 7.2 files and post update here. If it works then we can figure out contributing. I dont have any version info on the current files in used in the extensions folder. My current guess is some compatibility issue and may be few other places we might need to update to make it work. I would like to provide a solution for the community but I need to make it work first. My other doubt is that, since i am on specialty chip from AMD and not sure it will be universal fix either. Lets see where it goes

**Comment by kazu** [comment]
@yogeshbabu It seems my OpenClaw bot mistakenly posted this comment while monitoring this issue. I'll delete it now. Sorry for the noise!

**Comment by yogeshbabu** [comment]
I tried with 7.2 and with all latest 2.3.0 plugins and lmstudio 0.4.4
now i got this new error
```
Memory access fault by GPU node-1 (Agent handle: 0x3ba1d010) on address 0x7b35dd0c1000. Reason: Page not present or supervisor privilege.
```
I have setup GTT and Pages properly and system has full access to all of 125GB. Even studio UI detects everything as setup. But for some reason unable to load models using ROCm runtime.

<img width="1044" height="489" alt="Image" src="https://github.com/user-attachments/assets/e63a45c7-0657-4fb3-8856-beda86dd0657" />

**Comment by thehonestcto** [comment]
I am unable to load models with the ROCm runtime as well with MI210x.

Edit:
I build llama.cpp locally with the following flags for ROCM and it works fine with my GPUs when running directly from llama, no LM Studio. 
    -DGGML_HIP=ON \
    -DGGML_HIPBLAS=ON \
    -DAMDGPU_TARGETS=gfx90a \
    -DCMAKE_CXX_FLAGS="-mllvm --amdgpu-unroll-threshold-local=600" \
    -DCMAKE_HIP_COMPILER_ROCM_ROOT=/opt/rocm-7.2.0 \
    -DGGML_FLASH_ATTN=ON \
    -DGGML_HIP_ROCWMMA_FATTN=ON \
    -DGGML_HIP_UMA=OFF \
    -DCMAKE_PREFIX_PATH=/opt/rocm-7.2.0 \
    -DCMAKE_BUILD_TYPE=Release

**Comment by sirolf99** [comment]
why not include dep with llama build
like they did here : https://github.com/lemonade-sdk/llamacpp-rocm/releases/tag/b1217
with all essential ROCm runtime libraries included ?

**Comment by ccmmgg** [comment]
please fix!

**Comment by yogeshbabu** [comment]
I am also waiting for a fix on this.... Vulkan works but it struggles. For example if you use the new Gemma 4 it is crazy slow even though models in only 20GB.

Anyone has some working ROCm setup ?

**Comment by Kaihui-AMD** [comment]
Inspecting v2.21.0: the llama.cpp binary already lists gfx1151 as a compile target in backend-manifest.json — so no binary recompile is needed. What's broken is the bundled ROCm 6.4 runtime (linux-llama-rocm-vendor-v3), which has two issues on gfx1151:

1. VGPR size bug in ROCm 6.4 rocr-runtime — the hardware VGPR count for gfx1151 was reported incorrectly, fixed in ROCm 7.2+. This is why model loading results in Memory access fault even after copying Tensile files.
2.  Missing TensileLibrary_lazy_gfx1151.dat — the vendor rocBLAS has Tensile files for gfx1100/1101/1102/1200/1201 but not gfx1151. Native gfx1151 Tensile support is present in the standard ROCm 7.2 release (confirmed on ROCm 7.2.1). The practical workaround is HSA_OVERRIDE_GFX_VERSION=11.0.0 to fall back to gfx1100 kernels.

The vendor package needs to be updated to ROCm 7.2+ to fix both issues.
Workaround while waiting (both steps required):

1. Replace the vendor dir with ROCm 7.2 system libs:
```bash
VENDOR=~/.lmstudio/extensions/backends/vendor/linux-llama-rocm-vendor-v3
ROCM=/opt/rocm   # adjust if your ROCm is installed elsewhere
cp -r "$VENDOR" "${VENDOR}.bak"
find "$VENDOR" -maxdepth 1 -type f -delete
rm -rf "$VENDOR/rocblas"
find "$ROCM/lib" -maxdepth 1 -type f -exec cp -t "$VENDOR" -- {} +
cp -a "$ROCM/lib/rocblas" "$VENDOR/"
cp -a "$ROCM/lib/llvm" "$VENDOR/"
# Create version-compat symlinks
for lib in libhipblas.so.2 librocblas.so.4 libamdhip64.so.6 libhipblaslt.so.0; do
  base="${lib%.[0-9]*}"; newest=$(ls "$VENDOR/$base".* 2>/dev/null | sort -V | tail -1)
  [ -n "$newest" ] && ln -sfn "$(basename "$newest")" "$VENDOR/$lib"
done
```
2. Launch LM Studio with HSA_OVERRIDE_GFX_VERSION=11.0.0

**Comment by rugvedS07** [comment]
Hello! Sorry for the wait, the newest BETA llama.cpp engine (2.22.1) ships with ROCm 7!

**Comment by UMSGirl** [comment]
I can provide an update from a current `gfx1151` setup, because the situation seems to have moved beyond the original “ROCm support missing” problem described in this issue.

My system:

* AMD Ryzen AI Max+ 395
* Radeon 8060S
* `gfx1151`
* Linux Mint 22.3
* LM Studio
* `llama.cpp-linux-x86_64-amd-rocm-avx2@2.29.0`

The good news is that ROCm itself is now working on this hardware in LM Studio. Models load and Qwen models run correctly with the ROCm backend.

However, there appears to be a remaining correctness problem specifically with Gemma 4.

I tested multiple Gemma 4 variants. Under the ROCm backend they can collapse into endless reserved-token output such as:

```text
<unused24><unused24><unused24>...
```

or:

```text
<unused49><unused49><unused49>...
```

This is not just a model-loading failure. The model may start normally and then inference becomes corrupted.

The useful comparison is:

```text
gfx1151 + Qwen    + ROCm   -> works
gfx1151 + Gemma 4 + ROCm   -> <unused24>/<unused49> corruption
gfx1151 + Gemma 4 + Vulkan -> works correctly
gfx1151 + Gemma 4 + CPU    -> works correctly
```

I also tested a previous Linux kernel and the behavior remained the same, so this does not appear to be caused by the recent kernel update.

There are no obvious GPU crash symptoms either. I am not seeing `GPU reset`, `ring timeout`, `VM fault` or `amdgpu_job_timedout` messages.

This looks much more like a remaining Gemma 4 + HIP/ROCm correctness issue on `gfx1151` than a general Strix Halo ROCm support problem.

There is already a very relevant upstream llama.cpp report here:

`ggml-org/llama.cpp#26239`

That report describes the same class of `<unused49>` generation corruption on `gfx1151` with HIP, including evidence that batch/micro-batch boundaries may be involved.

Since current LM Studio ROCm engines now successfully support `gfx1151`, I think it would be useful to verify which exact ROCm version is bundled with the current `2.29.0` engine and whether the upstream Gemma 4 / HIP fixes or workarounds are already included.

This is especially important because Vulkan gives correct results with the same models on the same hardware. So this is no longer just a performance difference between Vulkan and ROCm. The ROCm path is producing incorrect inference results for Gemma 4.

I can run additional tests with specific `batch`, `ubatch`, context sizes or engine versions if that helps isolate the remaining issue.

Thx UMSGirl 👍
