### ISSUE TITLE
Bug Report: llama.cpp 2.13.0 Produces Garbled Output on Dual NVIDIA RTX A5000 (Linux/CUDA)

### ISSUE THREAD

**Issue by ChrisDotWDot** [lmstudio-ai/lmstudio-bug-tracker#1821]
<h2 class="text-text-100 mt-3 -mb-1 text-[1.125rem] font-bold">Summary</h2>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">llama.cpp runtime version 2.13.0, as bundled with LM Studio 0.4.12 (Build 1), produces completely garbled/corrupted output across all models on a dual NVIDIA RTX A5000 system running Ubuntu with CUDA 12.8. Rolling back to llama.cpp 2.7.1 (bundled with LM Studio 0.4.7) resolves the issue completely.</p>
<hr class="border-border-200 border-t-0.5 my-3 mx-1.5">
<h2 class="text-text-100 mt-3 -mb-1 text-[1.125rem] font-bold">Environment</h2>
<div class="overflow-x-auto w-full px-2 mb-6">
Component | Version
-- | --
OS | Ubuntu 24.04
Kernel | 6.8.0-106-generic
LM Studio (broken) | 0.4.12 (Build 1)
LM Studio (working) | 0.4.7 (Build 4)
llama.cpp (broken) | 2.13.0 (llama.cpp-linux-x86_64-nvidia-cuda-avx2)
llama.cpp (working) | 2.7.1 (llama.cpp-linux-x86_64-nvidia-cuda-avx2)
GPU 0 | NVIDIA RTX A5000 (24564 MiB VRAM)
GPU 1 | NVIDIA RTX A5000 (24564 MiB VRAM)
Total VRAM | 47.1 GB
NVIDIA Driver | 570.195.03
CUDA Version | 12.8
System RAM | 251.4 GB

</div>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">All models work correctly with llama.cpp 2.7.1.</p>
<hr class="border-border-200 border-t-0.5 my-3 mx-1.5">
<h2 class="text-text-100 mt-3 -mb-1 text-[1.125rem] font-bold">Steps to Reproduce</h2>
<ol class="[li_&amp;]:mb-0 [li_&amp;]:mt-1 [li_&amp;]:gap-1 [&amp;:not(:last-child)_ul]:pb-1 [&amp;:not(:last-child)_ol]:pb-1 list-decimal flex flex-col gap-1 pl-8 mb-3">
<li class="whitespace-normal break-words pl-2">Install LM Studio 0.4.12 (Build 1) on Ubuntu 24.04 with dual NVIDIA RTX A5000 GPUs</li>
<li class="whitespace-normal break-words pl-2">Ensure <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">llama.cpp-linux-x86_64-nvidia-cuda-avx2@2.13.0</code> is the selected runtime (<code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">lms runtime ls</code>)</li>
<li class="whitespace-normal break-words pl-2">Load any GGUF model</li>
<li class="whitespace-normal break-words pl-2">Send any prompt (e.g. "Hello")</li>
<li class="whitespace-normal break-words pl-2">Observe garbled/corrupted output</li>
</ol>
<hr class="border-border-200 border-t-0.5 my-3 mx-1.5">
<h2 class="text-text-100 mt-3 -mb-1 text-[1.125rem] font-bold">Expected Behaviour</h2>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">Normal coherent text response. For example with Qwen3.5 9B and "Hello":</p>
<blockquote class="ml-2 border-l-4 border-border-300/10 pl-4 text-text-300">
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">"Hello! 😊 How can I assist you today?"</p>
</blockquote>
<hr class="border-border-200 border-t-0.5 my-3 mx-1.5">
<h2 class="text-text-100 mt-3 -mb-1 text-[1.125rem] font-bold">Actual Behaviour</h2>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">Completely garbled output consisting of:</p>
<ul class="[li_&amp;]:mb-0 [li_&amp;]:mt-1 [li_&amp;]:gap-1 [&amp;:not(:last-child)_ul]:pb-1 [&amp;:not(:last-child)_ol]:pb-1 list-disc flex flex-col gap-1 pl-8 mb-3">
<li class="whitespace-normal break-words pl-2">Raw special tokens: <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">&lt;unused44&gt;&lt;unused47&gt;&lt;unused18&gt;...</code></li>
<li class="whitespace-normal break-words pl-2">Corrupted ASCII: <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">@%,(#1@6#A'!&amp;!4=E:BD...</code></li>
<li class="whitespace-normal break-words pl-2">Repeated question marks: <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">???????????????...</code></li>
</ul>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">The specific garbage pattern varies by model but is consistent and reproducible.</p>
<hr class="border-border-200 border-t-0.5 my-3 mx-1.5">
<h2 class="text-text-100 mt-3 -mb-1 text-[1.125rem] font-bold">GPU and Inference Verification</h2>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">Despite garbled output, GPU inference is confirmed working correctly:</p>
<ul class="[li_&amp;]:mb-0 [li_&amp;]:mt-1 [li_&amp;]:gap-1 [&amp;:not(:last-child)_ul]:pb-1 [&amp;:not(:last-child)_ol]:pb-1 list-disc flex flex-col gap-1 pl-8 mb-3">
<li class="whitespace-normal break-words pl-2">Both GPUs detected: <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">ggml_cuda_init: found 2 CUDA devices (Total VRAM: 48241 MiB)</code></li>
<li class="whitespace-normal break-words pl-2">Model layers fully offloaded to GPU: <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">load_tensors: offloaded 33/33 layers to GPU</code></li>
<li class="whitespace-normal break-words pl-2">VRAM correctly allocated across both GPUs</li>
<li class="whitespace-normal break-words pl-2">PyTorch CUDA test passes: <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">torch.cuda.is_available() = True</code>, matrix multiplication produces correct results</li>
<li class="whitespace-normal break-words pl-2">No XID errors in <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">dmesg</code></li>
<li class="whitespace-normal break-words pl-2">No ECC errors reported by <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">nvidia-smi</code></li>
<li class="whitespace-normal break-words pl-2">No missing CUDA library dependencies (<code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">ldd libggml-cuda.so</code> shows no "not found")</li>
</ul>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">This confirms the issue is in llama.cpp 2.13.0's inference logic, not in the hardware, driver, or CUDA installation.</p>
<hr class="border-border-200 border-t-0.5 my-3 mx-1.5">
<h2 class="text-text-100 mt-3 -mb-1 text-[1.125rem] font-bold">Runtime Details</h2>
<div role="group" aria-label="Code" tabindex="0" class="relative group/copy bg-bg-000/50 border-0.5 border-border-400 rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-100"><div class="sticky opacity-0 group-hover/copy:opacity-100 group-focus-within/copy:opacity-100 top-2 py-2 h-12 w-0 float-right"><div class="absolute right-0 h-8 px-2 items-center inline-flex z-10"><button class="inline-flex
  items-center
  justify-center
  relative
  isolate
  shrink-0
  can-focus
  select-none
  disabled:pointer-events-none
  disabled:opacity-50
  disabled:shadow-none
  disabled:drop-shadow-none border-transparent
          transition
          font-base
          duration-300
          ease-[cubic-bezier(0.165,0.85,0.45,1)] h-8 w-8 rounded-md backdrop-blur-md _fill_56vq7_9 _ghost_56vq7_96" type="button" aria-label="Copy to clipboard" data-state="closed"><div class="relative"><div class="transition-all opacity-100 scale-100" style="width: 20px; height: 20px; display: flex; align-items: center; justify-content: center;"><svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" class="transition-all opacity-100 scale-100" aria-hidden="true" style="flex-shrink: 0;"><path d="M12.5 3A1.5 1.5 0 0 1 14 4.5V6h1.5A1.5 1.5 0 0 1 17 7.5v8a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 6 15.5V14H4.5A1.5 1.5 0 0 1 3 12.5v-8A1.5 1.5 0 0 1 4.5 3zm1.5 9.5a1.5 1.5 0 0 1-1.5 1.5H7v1.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5H14zM4.5 4a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5z"></path></svg></div><div class="absolute inset-0 flex items-center justify-center"><div class="transition-all opacity-0 scale-50" style="width: 20px; height: 20px; display: flex; align-items: center; justify-content: center;"><svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" class="transition-all opacity-0 scale-50" aria-hidden="true" style="flex-shrink: 0;"><path d="M15.188 5.11a.5.5 0 0 1 .752.626l-.056.084-7.5 9a.5.5 0 0 1-.738.033l-3.5-3.5-.064-.078a.501.501 0 0 1 .693-.693l.078.064 3.113 3.113 7.15-8.58z"></path></svg></div></div></div></button></div></div><div class="overflow-x-auto"><pre class="code-block__code !my-0 !rounded-lg !text-sm !leading-relaxed p-3.5" style="color: rgb(20, 24, 31); background: transparent; font-family: var(--font-mono);"><code style="color: rgb(20, 24, 31); background: transparent; font-family: var(--font-mono); white-space: pre-wrap;"><span><span>LLM ENGINE                                          SELECTED    MODEL FORMAT
</span></span><span>llama.cpp-linux-x86_64-avx2@2.7.1                                   GGUF
</span><span>llama.cpp-linux-x86_64-nvidia-cuda-avx2@2.13.0         ✓            GGUF  ← broken
</span><span>llama.cpp-linux-x86_64-nvidia-cuda-avx2@2.7.1                       GGUF  ← working
</span><span>llama.cpp-linux-x86_64-vulkan-avx2@2.7.1                            GGUF</span></code></pre></div></div>
<hr class="border-border-200 border-t-0.5 my-3 mx-1.5">
<h2 class="text-text-100 mt-3 -mb-1 text-[1.125rem] font-bold">Workaround</h2>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">Switch to llama.cpp 2.7.1 via the CLI:</p>
<div role="group" aria-label="bash code" tabindex="0" class="relative group/copy bg-bg-000/50 border-0.5 border-border-400 rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-100"><div class="sticky opacity-0 group-hover/copy:opacity-100 group-focus-within/copy:opacity-100 top-2 py-2 h-12 w-0 float-right"><div class="absolute right-0 h-8 px-2 items-center inline-flex z-10"><button class="inline-flex
  items-center
  justify-center
  relative
  isolate
  shrink-0
  can-focus
  select-none
  disabled:pointer-events-none
  disabled:opacity-50
  disabled:shadow-none
  disabled:drop-shadow-none border-transparent
          transition
          font-base
          duration-300
          ease-[cubic-bezier(0.165,0.85,0.45,1)] h-8 w-8 rounded-md backdrop-blur-md _fill_56vq7_9 _ghost_56vq7_96" type="button" aria-label="Copy to clipboard" data-state="closed"><div class="relative"><div class="transition-all opacity-100 scale-100" style="width: 20px; height: 20px; display: flex; align-items: center; justify-content: center;"><svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" class="transition-all opacity-100 scale-100" aria-hidden="true" style="flex-shrink: 0;"><path d="M12.5 3A1.5 1.5 0 0 1 14 4.5V6h1.5A1.5 1.5 0 0 1 17 7.5v8a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 6 15.5V14H4.5A1.5 1.5 0 0 1 3 12.5v-8A1.5 1.5 0 0 1 4.5 3zm1.5 9.5a1.5 1.5 0 0 1-1.5 1.5H7v1.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5H14zM4.5 4a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5z"></path></svg></div><div class="absolute inset-0 flex items-center justify-center"><div class="transition-all opacity-0 scale-50" style="width: 20px; height: 20px; display: flex; align-items: center; justify-content: center;"><svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" class="transition-all opacity-0 scale-50" aria-hidden="true" style="flex-shrink: 0;"><path d="M15.188 5.11a.5.5 0 0 1 .752.626l-.056.084-7.5 9a.5.5 0 0 1-.738.033l-3.5-3.5-.064-.078a.501.501 0 0 1 .693-.693l.078.064 3.113 3.113 7.15-8.58z"></path></svg></div></div></div></button></div></div><div class="text-text-500 font-small p-3.5 pb-0">bash</div><div class="overflow-x-auto"><pre class="code-block__code !my-0 !rounded-lg !text-sm !leading-relaxed p-3.5" style="color: rgb(20, 24, 31); background: transparent; font-family: var(--font-mono);"><code class="language-bash" style="color: rgb(20, 24, 31); background: transparent; font-family: var(--font-mono); white-space: pre;"><span><span>~/.lmstudio/bin/lms runtime </span><span class="token token" style="color: rgb(129, 0, 194);">select</span><span> llama.cpp-linux-x86_64-nvidia-cuda-avx2@2.7.1</span></span></code></pre></div></div>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">Verify with:</p>
<div role="group" aria-label="bash code" tabindex="0" class="relative group/copy bg-bg-000/50 border-0.5 border-border-400 rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-accent-100"><div class="sticky opacity-0 group-hover/copy:opacity-100 group-focus-within/copy:opacity-100 top-2 py-2 h-12 w-0 float-right"><div class="absolute right-0 h-8 px-2 items-center inline-flex z-10"><button class="inline-flex
  items-center
  justify-center
  relative
  isolate
  shrink-0
  can-focus
  select-none
  disabled:pointer-events-none
  disabled:opacity-50
  disabled:shadow-none
  disabled:drop-shadow-none border-transparent
          transition
          font-base
          duration-300
          ease-[cubic-bezier(0.165,0.85,0.45,1)] h-8 w-8 rounded-md backdrop-blur-md _fill_56vq7_9 _ghost_56vq7_96" type="button" aria-label="Copy to clipboard" data-state="closed"><div class="relative"><div class="transition-all opacity-100 scale-100" style="width: 20px; height: 20px; display: flex; align-items: center; justify-content: center;"><svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" class="transition-all opacity-100 scale-100" aria-hidden="true" style="flex-shrink: 0;"><path d="M12.5 3A1.5 1.5 0 0 1 14 4.5V6h1.5A1.5 1.5 0 0 1 17 7.5v8a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 6 15.5V14H4.5A1.5 1.5 0 0 1 3 12.5v-8A1.5 1.5 0 0 1 4.5 3zm1.5 9.5a1.5 1.5 0 0 1-1.5 1.5H7v1.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5H14zM4.5 4a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5z"></path></svg></div><div class="absolute inset-0 flex items-center justify-center"><div class="transition-all opacity-0 scale-50" style="width: 20px; height: 20px; display: flex; align-items: center; justify-content: center;"><svg width="20" height="20" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg" class="transition-all opacity-0 scale-50" aria-hidden="true" style="flex-shrink: 0;"><path d="M15.188 5.11a.5.5 0 0 1 .752.626l-.056.084-7.5 9a.5.5 0 0 1-.738.033l-3.5-3.5-.064-.078a.501.501 0 0 1 .693-.693l.078.064 3.113 3.113 7.15-8.58z"></path></svg></div></div></div></button></div></div><div class="text-text-500 font-small p-3.5 pb-0">bash</div><div class="overflow-x-auto"><pre class="code-block__code !my-0 !rounded-lg !text-sm !leading-relaxed p-3.5" style="color: rgb(20, 24, 31); background: transparent; font-family: var(--font-mono);"><code class="language-bash" style="color: rgb(20, 24, 31); background: transparent; font-family: var(--font-mono); white-space: pre;"><span><span>~/.lmstudio/bin/lms runtime </span><span class="token token" style="color: rgb(0, 81, 194);">ls</span></span></code></pre></div></div>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">All models produce correct output after switching to 2.7.1.</p>
<hr class="border-border-200 border-t-0.5 my-3 mx-1.5">
<h2 class="text-text-100 mt-3 -mb-1 text-[1.125rem] font-bold">Diagnosis Timeline</h2>
<p class="font-claude-response-body break-words whitespace-normal leading-[1.7]">The following were ruled out during investigation before identifying llama.cpp 2.13.0 as the cause:</p>
<ul class="[li_&amp;]:mb-0 [li_&amp;]:mt-1 [li_&amp;]:gap-1 [&amp;:not(:last-child)_ul]:pb-1 [&amp;:not(:last-child)_ol]:pb-1 list-disc flex flex-col gap-1 pl-8 mb-3">
<li class="whitespace-normal break-words pl-2">❌ Chat template misconfiguration</li>
<li class="whitespace-normal break-words pl-2">❌ Flash Attention settings</li>
<li class="whitespace-normal break-words pl-2">❌ GGUF file corruption</li>
<li class="whitespace-normal break-words pl-2">❌ Missing CUDA libraries</li>
<li class="whitespace-normal break-words pl-2">❌ NVIDIA driver/kernel mismatch</li>
<li class="whitespace-normal break-words pl-2">❌ ECC memory errors</li>
<li class="whitespace-normal break-words pl-2">❌ GPU not being used (confirmed layers offloaded to GPU)</li>
<li class="whitespace-normal break-words pl-2">❌ LM Studio configuration files (fresh install reproduced the issue)</li>
<li class="whitespace-normal break-words pl-2">✅ <strong>llama.cpp 2.13.0 confirmed as root cause</strong></li></ul>

**Comment by Tom-Neverwinter** [comment]
how do we replace this version with a proper version: https://github.com/ggml-org/llama.cpp like: https://github.com/ggml-org/llama.cpp/releases/tag/b8840 and we can all move on with our lives.

**Comment by Starfiresg1** [comment]
I have this issue too with a 5070Ti on Windows. Responses are either garbled, short nonsense or completely empty. So it seems OS independent. It seems to also be tied to 2.13.0 - the previous version 2.12.0 is working for me.
