### ISSUE TITLE
(0 GPUs, ROCm stuck at 100%, Stubborn runtime download button) - New Adrenalin 26.5.1 Drivers make ROCm llama.cpp runtime crash during hardware survey on RX 9070 XT (Windows) with unclean `loadLib/getLib` exception handling

### ISSUE THREAD

**Issue by Jamroszczyk** [lmstudio-ai/lmstudio-bug-tracker#1906]
Issue Synopsis:

ROCm in the newest Adrenalin 26.5.1 release causes a poorly handled exception in LM Studio runtime loader, making the ROCm runtime unusable and potentially breaking runtime management after failed loading attempts, affecting all other runtimes, resulting in infinite model indexing time, 0 detected GPUs, runtime downloading UI element stuck at 100% / extracting files forever. This is effectively system-breaking for ROCm usage on the described setup and is messing up the runtime management upon relaunch. This is causing issues for many users with similar hardware, as rerolling to previous ROCm runtimes is no longer available in the LM Studio Desktop App on Windows. The ROCm llama.cpp runtime cannot be used at all on the below-described RX 9070 XT, with current Adrenalin drivers on Windows systems. 
The runtime crashes during initialization/hardware survey specifically and deregisters itself afterward. On fresh install Vulkan can  work correctly on the same hardware until relaunch (if ROCm was attempted to be installed), so this currently leaves no functional way to use the ROCm backend in LM Studio on this configuration.

Software specific details:

LM Studio Version 0.4.12 (Build 1)
Adrenalin Version 26.5.1
ROCm llama.cpp (Windows) v2.13.0

Failing runtime:
* ROCm llama.cpp (Windows) v2.13.0
* llama.cpp release b8733 (commit d6f3030)

Working runtime on fresh install:
* Vulkan llama.cpp (Windows) v2.13.0

**Details about the system where this issue was observed**

OS
* Windows 11 Pro 25H2
* OS Build: 26200.8246
* Windows Feature Experience Pack: 1000.26100.297.0

System:

* CPU: AMD Ryzen 7 7800X3D
* RAM: 32 GB
* GPU: AMD Radeon RX 9070 XT (16 GB VRAM)
* Adrenalin 26.5.1 (04.05.2026 release)
* Additional GPU: AMD Radeon(TM) Graphics (iGPU)

Architecture:

* x64

Date observed:

* 2026-05-11

---

**Details about the bug**

The ROCm llama.cpp runtime on Windows repeatedly fails during backend initialization/hardware survey on an AMD RX 9070 XT.

Behavior:

* Runtime downloads successfully
* Runtime extracts successfully
* Hardware survey begins
* Runtime deregisters/disappears again
* LM Studio throws an uncaught exception

The Vulkan backend works correctly on the same machine and correctly detects:

* GPU
* VRAM
* Vulkan compute support
* GPU offloading

This appears to specifically affect the ROCm backend/runtime initialization path.

Most relevant error in logs was:

```txt
Uncaught Exception: Error: You must call loadLib before using getLib
```

The crash consistently happens immediately after:

```txt
[BackendManager] Performing custom requested engine-hardware survey for engine 'llama.cpp-win-x86_64-amd-rocm-avx2@2.13.0'
```

The issue and state persists after:

* full uninstall,
* removing AppData/cache/.lmstudio and related temp folders and data,
* reboot,
* clean reinstall.
* Adrenalin 26.5.1 (04.05.2026 release) hardware driver reinstall

This suggests:

1. Vulkan support is functioning correctly.
2. The issue is specific to ROCm initialization/runtime management.
3. LM Studio may not gracefully handle a ROCm backend initialization failure after Adrenaline driver updates anymore.

---

**Relevant Logs**

Most relevant crash:

```txt
14:35:06.431 > Uncaught Exception: Error: You must call loadLib before using getLib
    at Object.get (C:\Users\xxxxx\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:294:22429)
    at Object.onceWrapper (node:events:630:17)
    at _0x43a09a.emit (node:events:531:35)
    at _0x43a09a.onChildExit (C:\Users\xxxxx\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:216:27995)
    at _0x43a09a.onChildExit (C:\Users\xxxxx\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:229:12533)
    at _0x497427.<anonymous> (C:\Users\xxxxx\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:216:27134)
    at _0x497427.emit (node:events:519:28)
    at ForkUtilityProcess.<anonymous> (C:\Users\xxxxx\AppData\Local\Programs\LM Studio\resources\app\.webpack\main\index.js:964:23521)
    at ForkUtilityProcess.emit (node:events:519:28)
    at ForkUtilityProcess.a.emit (node:electron/js2c/browser_init:2:74657)
```

ROCm runtime downloads successfully:

```txt
backend-llama.cpp-win-x86_64-amd-rocm-avx2-2.13.0.tar.gz
vendor-win-llama-rocm-vendor-v5.tar.gz
```

Extraction succeeds:

```txt
[RuntimeIndexerTarGzExtractionPostDownloadActionExecutor] Post-download tar.gz extraction took 9094ms
```

Immediately afterward:

```txt
[BackendManager] Performing custom requested engine-hardware survey for engine 'llama.cpp-win-x86_64-amd-rocm-avx2@2.13.0'
```

Then LM Studio crashes with the `loadLib/getLib` exception. "You must call loadLib before using getLib
"

Vulkan backend survey succeeds:

```txt
[BackendManager] Survey for engine 'llama.cpp-win-x86_64-vulkan-avx2@2.13.0' took 277.32ms
```
---

**To Reproduce**

1. Install LM Studio 0.4.12 (x86 Windows version) on matching hardware with declared software and driver versions.
2. Open Runtime settings
3. Download `ROCm llama.cpp (Windows) v2.13.0`
4. Wait for runtime extraction/indexing
5. LM Studio begins backend hardware survey
6. Runtime disappears/deregisters
7. 0 GPUs detected

Expected behavior:

* ROCm runtime should initialize successfully or at least fail gracefully with a compatibility message, as debugging this was super stressful without it.

**Likelly related Issues**

https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/1899
https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/1825

Workaround that works currently:

1. Uninstall/fully erase LM Studio AND then remove any local LM Studio-specific files and folders left in any of these folders if they exist. (Electron apps keep numerous files on the local machine even after using an official uninstall wizard.)

C:\Users\<your-user>\.lmstudio
C:\Users\<your-user>\AppData\Local\Programs\LM Studio
C:\Users\<your-user>\AppData\Roaming\LM Studio
C:\Users\<your-user>\AppData\Local\LM Studio
C:\Users\<your-user>\AppData\Local\Temp
 
2. Wipe AMD drivers completely using AMD's Cleanup Utility fully (https://drivers.amd.com/drivers/amdcleanuputility.exe)
3. Reboot your system.
4. THIS IS THE MAIN WORKAROUND: Download the preceding AMD Adrenalin version 26.3.1 and install it cleanly. (https://drivers.amd.com/drivers/whql-amd-software-adrenalin-edition-26.3.1-win11-c.exe)
5. Reboot your System once more.
6. Fresh Install of LM Studio 0.4.12+1
7. Download and let Install the ROCm runtime via the LM Studio runtime window.

**Comment by qqeew1234** [comment]
I am screaming  it is Radeon again,
i just trans to amd for 3days happend this issue

**Comment by ygolomeg** [comment]
instead of reinstalling LM studio, i was able to:
1) do amd cleanup 
2) reboot 
3) install amd driver 26.3.1
4) run **lms runtime ls**
5) run **lms runtime remove <name of ROCm install>** 
6) run **lms runtime get ** navigate, selecting ROCm
-- it got stuck at 0% for me at this step, so do ctrl + c to cancel, then N to confirm
7) run **lms runtime get** again, and select ROCm again, and it worked

**Comment by RenZekta** [comment]
yep, 9070 xt, same issue, rocm backend is downloaded but lm studio doesn't see it. I even got a black screen for some reason. Reinstalling lm studio doesn't help. even more, lm studio refused to see any backend as installed. deleting all of them worked for me, but rocm still isn't available.

**Comment by chreds** [comment]
I had to downgrade the AMD driver and clear out a bunch of lm studio cache and backend / framework configs to get it working again. Thanks to @Jamroszczyk for the detailed debugging here.

**Comment by Jamroszczyk** [comment]
> yep, 9070 xt, same issue, rocm backend is downloaded but lm studio doesn't see it. I even got a black screen for some reason. Reinstalling lm studio doesn't help. even more, lm studio refused to see any backend as installed. deleting all of them worked for me, but rocm still isn't available.

Did you try cleaning all AMD drivers and rolling back to Adrenalin 26.3.1 as described above? that should get your ROCm working again until the issues with the new drivers are resolved.

**Comment by RenZekta** [comment]
@Jamroszczyk nah I'm fine with Vulkan, and I barely use local ai stuff anyway. But if this level of "support" from AMD will continue, I'll probably buy Nvidia as next gpu. Hopefully they'll fix their power connector by that point.

**Comment by RenZekta** [comment]
Nope i gotta install the old one. even vulkan refuses to be recognized. I'll write if it helped.

**Comment by RenZekta** [comment]
Ok I simply downgraded the driver to 26.3.1 via quick install, rebooted, and its all normal now, even with rocm @Jamroszczyk 
clearly a driver incompatibility issue

**Comment by leonardopereira10** [comment]
@RenZekta the ROCm/HIP package of llama.cpp still working fine, the error is only on lmstudio implementation

tested on llama-b9093-bin-win-hip-radeon-x64 and llama-b8407

**Comment by albertgracia** [comment]
Mismo problema. Ryzen 7 7800X3D 64GB DDR5 RX9070 , Desinstalo LMSTUDIO desde desinstalador, borro todas las carpetas que hacen referencia a LMSTUDIO del sistema, con DDU desinstalo ultima versión Adrenaline 26.5.1 y la bajo a 26.3.1 reinicio Windows 11 , instalo LMSTUDIO de nuevo y ya me vuelve a aparecer RX9070 pero solo me trabaja ROCm llama.cpp (Windows) v2.14.0 AMD ROCm accelerated llama.cpp engine los demás en rojo. Bueno algo es algo. Antes me funcionaban todos los  Engines & Frameworks perfectamente actualizaban bien y cargaban todos. Creo que han sido los nuevos drivers de Adrenaline que ha roto la versión de LMSTUDIO, podían ir con un poco de cuidado y suerte que te recomiendan ellos LMSTUDIO en Adrenaline, los de AMD últimamente se están volviendo unos impresentables en este aspecto con lo bien que iban...

**Comment by IcarusV2X** [comment]
I had the same problem today ROCm was hanging up everything in LM Studio so I went to C:\Users\ [user] \.lmstudio\extensions\backends and deleted the ROCm folder from there. Then once I started LM Studio again it defaulted to Vulkan which works for me. AMD RX 9070 XT.

**Comment by Dycast** [comment]
Just starting to figure this out, same issue Win 11 latest beta, 9060xt, latest amd drivers, AMD Ryzen 7700xt. half the models disappeared from view with infinite indexing, and models fail to load.. Says I still have all models but cant locate some on drive. Hardware says 0 GPUs and downloading shows success, marks good, then reverts to download, only shows 'harmony' driver installed, appears to have happened a few days prior to latest lmstudio upgrade, which had no affect.

**Comment by Dycast** [comment]
Well, I was curious... So first I tried mentioned above, but I didn't have a ROCm folder - so I just wiped the folder. That did get it 'running' but only with Vulkan, and did not seem 'stable' .. So considering AMD ships with AI software, it made me wonder..  I removed LM Studio, went to the AMD AI Software updates page, and installed LM Studio from there... Again, I suppose you COULD say that it works ... Albeit, again with Vulkan drivers ONLY as this reverted LM Studio to v.0.3.28 .. Jeez, dissapointing.. Guess I'll go run AMD cleanup now..

**Comment by RenZekta** [comment]
@Dycast you only need to install previous driver version with quick install

**Comment by willgart** [comment]
Hi, in my case, I'm not able to install and use any of the runtimes.
I download each of them, but after few seconds, the download message is displayed again.

<img width="706" height="420" alt="Image" src="https://github.com/user-attachments/assets/4b54c9e1-ef0b-4dbd-96a5-2e0f8db27144" />

even using the lms command line tool, same result.

**Comment by Dycast** [comment]
Yep, same deal.. Roll back to 26.3.1 and it will all work fine again. @willgart

**Comment by Scorpiopt** [comment]
same issue but rollback didn't work , lm studio reinstall works once but just with vulkan no rocm .
specs are same has OP but i am using windows 11 LTSC

**Comment by Cromeroo** [comment]
same issue, after doing a little research, it seems like it might be a problem with ROCM, so I tried running it through Vulkan but couldn't

**Comment by PiRomant** [comment]
Deleting all `*rocm*` in `.lmstudio\extensions\backends` helped. (Adrenalin  26.5.2, LM Studio 0.4.13 (Build 1)

**Comment by albertgracia** [comment]
Me paso lo mismo. Vuelve a la versión 26.3.1 y todo volverá a funcionar correctamente:

**Comment by Dycast** [comment]
Same question as I asked in another issue on this or similar topic, can anyone confirm that they ARE using VRAM, and what direction they went to fix there setup? (Rollback lm studio or amd) I think I have an old driver still stuck in the mix, as I see both AMD Rx9060XT and AMD Raydeon as video drivers with adrenaline 26.3.1, I THINK this is causing an issue where it attempts to load to GPU, but onky sees a small amount so then loads the rest to a 'shared' VRAM ie: RAM, detected by using Task Manager -> Performance tab, load a model GPU ram spikes momentarily, and then RAM usage raises, can also be seen in adrenalin metrics by watching both RAM and GPU RAM. Fuethermore can be seen due to having 2 GPUs listed in Adrenaline..

**Comment by brano-p** [comment]
Same problems here, even with newer Adrenaline (what a suitable name!) 26.5.2 and LM Studio 0.4.14 (build 4). Runtimes (all of them) tell me that I should download them, but as soon as the download is complete (and the files are really there!) the Download button reappears. Model indexing lasts forever. No hardware shown, 0GB VRAM, etc.

I've just filed an issue from within AMD SW Adrenaline Edition - System tab. Please consider do the same so that the guys see that something is happening (unless they already know!). 
Fingers crossed.

**Comment by qqeew1234** [comment]
It has already been three weeks, yet the issue remains unresolved.

I submitted a report three weeks ago, but AMD has not responded at all—I am not sure if they are even recognizing the issue or if they simply cannot fix it—which is truly deplorable.

**Comment by Dycast** [comment]
Pretty sure its just as much LM Studio, considering nunerous other programs
work just fine - ie: Ollama with OpenWebUI which I'm moving to.

**Comment by leonardopereira10** [comment]
@qqeew1234 , is not just amd, the problem is on LMStudio veriffy, on original llama.cpp taths works fine

**Comment by enpinion** [comment]
To devs: Rebuild the ROCm llama.cpp with ROCm 7. Because the latest (since 26.5.1) driver removed ROCm 6 support for RDNA3/4.

Or let user build their own library.

**Comment by Silent1-art** [comment]
I've been troubleshooting LM Studio issues with the latest AMD drivers based on ROCm 7. I'm trying to fix it myself, and I'm almost there.

I rebuilt the vendor backend using **amdhip64_7.dll** along with the other ROCm DLLs, and I'm running a custom **llama.cpp Windows ROCm AVX2 build** compiled from the latest **llama.cpp** sources.

I'm also using **ROCm 7.13.0 for Windows with TheRock**, which is already working correctly in my PyTorch development environment.

On Windows, the vendor backend and extensions that need to be rebuilt are located in:

`C:\Users\<username>\.lmstudio\extensions\backends\`

The LM Studio interface is finally working again with the latest AMD drivers (**26.6.1**, also tested on **26.5.1** and **26.5.2**), whereas the Vulkan and ROCm engine,model indexing had completely stopped working.

After rebuilding some dependencies by myself, everything is starting to work again. Tested with **Qwen 3.6**, and the model is finally loading and generating responses correctly with Vulkan engine, almost with ROCm.

<img width="1051" height="398" alt="Image" src="https://github.com/user-attachments/assets/3093c839-5145-461a-8e4e-5f1f7d0fe21b" />

<img width="1806" height="1140" alt="Image" src="https://github.com/user-attachments/assets/7c39f748-e5dc-493f-8e4b-717ea5afd916" />

This issue has been around for several weeks now, and I'm just an end user. If I can get this close to a working fix on my own by rebuilding the vendor and updating its dependencies, what's going on? Has anyone on the LM Studio side looked into this yet?

**Comment by Dycast** [comment]
Doubt it, my understanding the backend is written wrong or we never would of had this, it shouldn't be proprietary to ROCm here, if that would of stayed on llama.cpp side this never would of been an issue.. AMD has looked into it and discovered it wasnt there code, it was how the backend is written, thats why all other apps using llama work fine, pytorch, open-webui, comfyui, except for another issue unrelated, etc. I was looking at doing the same, but PGE decided to cut down trees today, so no power/internet.. left me working on cars in the sun..

**Comment by Silent1-art** [comment]
Finished: working. Thanks, Codex.
5 minutes to finish debugging, now fully working.
I can enjoy LM Studio again.

<img width="1806" height="1146" alt="Image" src="https://github.com/user-attachments/assets/d5ed0dfd-bb93-46d3-8fdb-19ae778066d8" />

<img width="1806" height="1146" alt="Image" src="https://github.com/user-attachments/assets/ad56b40e-b17c-4564-871a-8cc345072f7d" />

I copied the ROCm vendor v5 as a baseline, rebuilt a new vendor v6 from scratch using the latest TheRock ROCm build, and mapped the LM Studio ROCm extension to use this v6 vendor.  
from backend llama.cpp-win-x86_64-amd-rocm-avx2-2.19.1\backend-manifest.json =>
 "vendor_lib_package_names": [
    "win-llama-rocm-vendor-**v6**"
  ],

After fixing the DLL resolution and rocBLAS/Tensile manifest paths, the backend now loads correctly with the new ROCm v6 setup.


LM Studio’s ROCm GPU survey failed because Windows loaded C:\Windows\System32\amdhip64_7.dll before the TheRock/vendor DLL.
Patched the ROCm backend imports from amdhip64_6.dll to amdhip64_7.dll and added gfx1200/gfx1201 targets.
Regenerated TensileManifest.txt for both the vendor v6 rocBLAS library and C:\TheRock\build\bin\rocblas\library.   ( Build from ROCm 7.13.0 ( preview) )
Copied the TheRock amdhip64_7.dll into the backend folder so it is resolved before System32.  
Validation now succeeds: LMSCore.surveyHardware() detects RX 9070 XT as ROCm gfx1201 with ~15.92 GB VRAM.

**Comment by Dycast** [comment]
Any chance you want to share? Would be greatly appreciated by a lot I'm sure, I wanted to do similar was going to try starting with the unlocked backends and add rocm, after power outage I worked on 1 car and now have two more that want my attention, I would rather work on computers than cars anymore, but the cars still pay.. Nice job! I'm  going to forward to a few on AMD forums

**Comment by Dycast** [comment]
The DLL load is a known issue, the right one needs to load towards the top, especially before usage.. to get the right one loading first check your Environment (type edit environment in Search on taskbar) Then make sure the ROCm dll you want is loaded before any others, and before LM Studio. - Passing that along from AMD's Discord bot which brought it up while a few of us were talking about this issue.

**Comment by Silent1-art** [comment]
I created a script that can help repair LM Studio ROCm integration. Use it at your own risk or juste understand the purpose. ( it just copy past file from folders... and fix import ...)

Follow AMD’s ROCm local build documentation first: https://rocm.docs.amd.com/en/7.13.0-preview/install/rocm.html?fam=radeon&w=compute&os=windows&windows-ver=11&i=tar&gpu=ai-r9700&gfx=gfx1201

Start from a clean LM Studio setup by removing existing extensions and vendors, then let LM Studio download them again. Close LM Studio, run the repair script, then restart LM Studio.

<img width="1806" height="1146" alt="Image" src="https://github.com/user-attachments/assets/3d9cd337-b12a-4be8-a4d9-bd117ba9d943" />
run script then open lm studio 

<img width="1806" height="1146" alt="Image" src="https://github.com/user-attachments/assets/23c17efa-8b19-4b46-9369-1879fb46bcfb" />

config model : 

<img width="1812" height="1158" alt="Image" src="https://github.com/user-attachments/assets/07bc00c9-1cd9-42ba-9db7-557f729f0344" />

Due to the workaround applied in this setup, a current ROCm/LM Studio issue can occur when reloading conversations with history. Adjust the model load settings manually. For example, set eval batch size to 64 and physical batch size to 1.

<img width="1812" height="1158" alt="Image" src="https://github.com/user-attachments/assets/fbc56d6a-f9c3-45fb-8d22-2f74ab5a7228" /> 

[repair_lmstudio_rocm_therock.py](https://github.com/user-attachments/files/28557265/repair_lmstudio_rocm_therock.py)

At this point, further fixes are outside my scope and should be handled upstream. AMD’s undocumented changes created compatibility issues, but LM Studio should also avoid being this tightly dependent on fragile ROCm vendor packaging details.

**Comment by hammerjoe** [comment]
I have the same issue with the latest adrenaline drivers 26.6.1 and Lmstudio would not see the 9070XT but I think I found a fix that seems to be working.

in the folder C:\Users<your-user>\AppData\Local\Programs\LM Studio just remove the file vulkan-1.dll and start lmstudio. It will prompt to fix the runtimes but the GPU should be recognized properly.

**Comment by dielianjunmobei** [comment]
> I have the same issue with the latest adrenaline drivers 26.6.1 and Lmstudio would not see the 9070XT but I think I found a fix that seems to be working.
> 
> in the folder C:\Users\AppData\Local\Programs\LM Studio just remove the file vulkan-1.dll and start lmstudio. It will prompt to fix the runtimes but the GPU should be recognized properly.

I tried it, but it doesn't seem to have prompted me to repair it.

**Comment by hammerjoe** [comment]
> > I have the same issue with the latest adrenaline drivers 26.6.1 and Lmstudio would not see the 9070XT but I think I found a fix that seems to be working.
> > in the folder C:\Users\AppData\Local\Programs\LM Studio just remove the file vulkan-1.dll and start lmstudio. It will prompt to fix the runtimes but the GPU should be recognized properly.
> 
> I tried it, but it doesn't seem to have prompted me to repair it.

If you go to the runtimes page it will show you the runtimes. If theres no buttons, then theres nothing to do. Does the GPU show up anyway?

**Comment by Dycast** [comment]
New Versions! While I'm unsure about a complete fix, I would like to say I see progress!!

LM Studio v 0.4.16
AMD Adrenaline v26.6.1

Aside from the Models and Hub directories, I did a clean install of LM Studio, I've yet to be able to get the ROCm drivers working, however, my GPU is showing up, and it appears Vulkan drivers are installed!

Also, just loaded a model, and can confirm with Vulkan drivers it IS loading to GPU! Hopefully the ROCm drivers get situated soon, but this is a great step!

Ok, so  tried downloading ROCm driver, caused a hang, then on reload was back to 0 GPU, and all drivers needing download, which stuck for a few seconds, and needed again... Closed out, went to Backends directory, deleted the ROCm driver, as well as CUDA, since that is just wasting space.. Reload, and its working again. Vulkan drivers appear fixed, I think ROCm drivers are still needing work, from what I saw, I think the ROCm driver is still trying to use ROCm v6 instead of v7, (going off name of a file I saw before deleting, Amdhip64_6.dll, which I'm pretty sure references for version 6 not 7, and my understanding is they are not backwards compatible.

However, it is still running, with Vulkan, and with that glitch figured out, I believe its fairly stable, and just needing a compatible ROCm 7 llama driver

**Comment by galmok** [comment]
> I created a script that can help repair LM Studio ROCm integration. Use it at your own risk or juste understand the purpose. ( it just copy past file from folders... and fix import ...)
> ...

I followed your guide and used your script, and after some confusion why ROCm wouldn't load in LM Studio, I just had to make LM Studio re-evaluate the ROCm validity and it just worked. I get 51 tps from Gemma 12B on my 9070 XT and that is good enough for me. Thanks.

Edit: After my first two successful queries, every following query fails. I get this error:
CUBLAS_STATUS_NOT_SUPPORTED
Restarting LM Studio doesn't help.
At least Vulcan works and is almost as fast (50 tps vs 51 tps).

**Comment by Redbird10** [comment]
This is what I did on my side. It does not fix the ROCm backend itself, but it cleared the stuck 100% runtime state and lets LM Studio return to a usable state without rolling back the AMD driver.

In my case, I removed the ROCm backend under:

```text
C:\Users\<your-username>\.lmstudio\extensions\backends
```

Then I deleted the stuck download job state:

```text
C:\Users\<your-username>\.lmstudio\.internal\download-jobs-info.json
```

I also made sure the preferred backend was no longer set to ROCm, by checking:

```text
C:\Users\<your-username>\.lmstudio\.internal\backend-preferences-v1.json
```

After that, the stuck loading state was gone, and I could keep using LM Studio without ROCm, e.g. with Vulkan.

**Comment by qqeew1234** [comment]
These people at LM Studio aren't doing their job with Radeon support.

I understand that nobody uses Radeon, but...

If it doesn't work due to a bug, they should either block support or fix it quickly. Why have they just left it alone without saying a word for over a month?

I don't think this is the proper way to handle things.

**Comment by dielianjunmobei** [comment]
> > > I have the same issue with the latest adrenaline drivers 26.6.1 and Lmstudio would not see the 9070XT but I think I found a fix that seems to be working.
> > > in the folder C:\Users\AppData\Local\Programs\LM Studio just remove the file vulkan-1.dll and start lmstudio. It will prompt to fix the runtimes but the GPU should be recognized properly.
> > 
> > 
> > I tried it, but it doesn't seem to have prompted me to repair it.
> 
> If you go to the runtimes page it will show you the runtimes. If theres no buttons, then theres nothing to do. Does the GPU show up anyway?

The GPU isn't showing up; it's the same as before.

**Comment by Dycast** [comment]
Delete the ROCm drivers and GPU will show up, Vulkan works, confirmed loading to video card not RAM..

I'm seriously bout done with this BS program though. Lemonade works, with ROCm, like 5 minute setup. Llama.cpp with Open-WebUI works, with ROCm no problems, little longer setup, both also have inference options.

If these guys dont want to fix problems, listen or talk to the people wanting to use the program, they dont have a very bright future. Heard again they are trying to blame it on AMD, it is 1000% LM Studio, if it WAS AMD, how come this is the ONLY program that has issues? Both Lemonade, Llama, Ollama, and nunerous others work with ROCm 7 NO PROBLEM. Ditch this crap and get an open-source program before these guys put up a pay wall on there buggy ass software..

**Comment by ChristopherBull** [comment]
This is ridiculous. I am migrating back to Ollama as they've recently added Vulkan support for AMD.

**Comment by mironoff2007** [comment]
same on 26.6.1 9060xt lm studio 0.14.17

**Comment by leonardopereira10** [comment]
@mironoff2007 change to llama.cpp with openwebui, i made a fork with auto download of rocm versions, that not merged also

<img width="1478" height="785" alt="Image" src="https://github.com/user-attachments/assets/85541fa1-5fd8-4084-b625-56b0067fc73a" />

<img width="1461" height="805" alt="Image" src="https://github.com/user-attachments/assets/f5c6aa05-56d8-4c90-9431-954711785339" />

**Comment by brano-p** [comment]
This issue appears to be fixed now with 0.4.17 (Build 2), see release notes at https://lmstudio.ai/beta-releases
"Fixed bug where AMD GPUs were not detected due to driver updates. RESTART REQUIRED"
(9060XT/16G here)
<img width="693" height="595" alt="Image" src="https://github.com/user-attachments/assets/8332276e-ece9-4371-a3c4-710a6dcb6e70" />

**Comment by jtaylor-ion** [comment]
I can verify that Brano is correct. I just updated my Adrenaline drivers from 26.3.1 to 26.6.1 and LM Studio still works and sees my 9060 XT. NOTE: I am using LM Studio 0.4.17 - build 2.

**Comment by RenZekta** [comment]
For me (9070 xt, LM Studio 0.4.17 build 2, latest radeon drivers) issue still persits. 

Upon downloading ROCm engine it quickly becomes available to download again, and after an app restart, all runtimes exept harmony appear uninstalled and GPU isn't getting detected anymore in LM Studio. 

Deleting ROCm engine recovers an app, but limits it to Vulkan engine.

**Comment by jtaylor-ion** [comment]
Are you on the beta channel? I think you need to be on that channel to get the latest fixes.

**Comment by RenZekta** [comment]
> Are you on the beta channel? I think you need to be on that channel to get the latest fixes.

Yep, updated comment to clarify

**Comment by kwinz** [comment]
On Windows 11 (Version `10.0.26100.8457`) with RX 9070 XT and driver `26.6.1` from 2026-05-29
switching to the beta update channel and installing `0.4.17 (Build 2)` fixed the issue for me.
Both ROCm (`v2.22.1`) and Vulkan (`v2.22.0`) runtimes work.

I am happy that it's finally fixed after multiple weeks. But I have to say the fix took a trust shattering long time.

The error message were also very unhelpful. Instead of clearly stating what the error was the first sign that something was not working was simply that the installed models took forever to list. So there is a lot of things that could be improved to avoid this situation in the future.

**Comment by IcarusV2X** [comment]
I'm on RX 9070 XT,  Adrenalin 26.6.1, Lm studio version 0.4.17 Beta build 3, I managed to download the ROCm runtime but it says Error surveying hardware under it, at least it doesn't freeze the whole program and stops you from changing runtimes but still doesn't work. If I select the ROCm runtime and try to load a model it displays an error in the right corner which says: Failed to load the model / Engine protocol runtime llama-server for EmrBATkW5Lxm13+86pQdbM0f exited before becoming healthy. exitCode=3221225781, signal=null.

**Comment by brano-p** [comment]
@RenZekta did you erase all the backends and frameworks? That helped in my situation. I've closed the app, deleted all  backends and frameworks in C:\Users\<user>lmstudio\extensions folder, then re-launched, switched to display Beta updates (for the app), upgraded to 0.4.16 (Build 2, now 3 is available) and subsequently everythyng started to work as normal, including Vulkan and ROCm.

**Comment by RenZekta** [comment]
tested build 3, rocm now doesn't become invisible to lm studio after downloading, but ROCm engine still isn't available. Adrenaline 26.6.1, RX 9070 XT.

<img width="727" height="707" alt="Image" src="https://github.com/user-attachments/assets/4ade4122-1709-4de8-a1f7-b4a02728fbc5" />

**Comment by Dycast** [comment]
I find it rather strange that its apparantly working for some and not others.. Mabye further comparison of systems could narrow something down.. 

I have Win 11 on latest Insiders build (dont think that would matter)
Adrenaline latest version, 26.x.x (not in front of it)
LM Studio latest Betas, all 3 Beta channels open

AMD Ryzen 7700X CPU with iGPU disabled in BIOS
ASUS Max Gaming B850 WiFi 6e Motherboard
32GB DDR 5 Corsair Vengeance RAM

Software to note - TheRock ROCm installed - mention because of the environment paths for HIP and ROCm,

I cant think of anything else that would affect this, just wondering if anyone with problems is similar or if its running on someone's that has same hardware or The Rock drivers installed.. Or mabye spark someone else to have an aha moment?

**Comment by galmok** [comment]
I also get the "GPU survey unsuccessful" with ROCm runtime. I am using LM Studio 0.4.19 and have tried stable (v2.24.0) and beta (v2.25.0) ROCm runtime versions. Same result. I am running 26.6.4 for my 9070XT and the 9850X3D (iGPU). 

Starting LM Studio from the commandline (to get some log output) shows this:
[BackendManager] Performing custom requested engine-hardware survey for engine 'llama.cpp-win-x86_64-amd-rocm-avx2@2.25.0'
13:06:02.770 > No ROCm supported accelerators found!

No errors, just no devices detected.

I have tried to set HIP_VISIBLE_DEVICES=1, but that changed nothing. This used to solve 

I have also tried with TheRock 7.13 (windows) and while hipinfo does report the existance of both dGPU and iGPU, this did nothing to LM Studio.

**Comment by leonardopereira10** [comment]
@galmo try clear the runtimes folder...

and also the ROCm device 1 is only the iGPU, use HIP_VISIBLE_DEVICES=0,1 but this iGPU not run rocm properly, the best for u are no set visible devices

**Comment by galmok** [comment]
> [@galmo](https://github.com/galmo) try clear the runtimes folder...
> 
> and also the ROCm device 1 is only the iGPU, use HIP_VISIBLE_DEVICES=0,1 but this iGPU not run rocm properly, the best for u are no set visible devices

With Vulcan, both iGPU and dGPU work (iGPU show, though).  I am not sure which folder is the runtimes folder, but I have tried deleting the extensions folder  and have LM Studio repopulate it, but it never worked.

I have tried with all sort of combinations with that environment variable, including 0,1 and not setting it.
