### ISSUE TITLE
Vulkan llama.cpp v1.12.0 (Windows) Error surveying hardware (GPU) Intel Arc A770 16GB

### ISSUE THREAD

**Issue by Slurpeeguy** [lmstudio-ai/lmstudio-bug-tracker#379]
LM Studio 0.3.9 (Build 5)
Runtime: Vulkan llama.cpp v1.12.0 (Compatible) [Error surveying hardware] & CPU llama.cpp v1.11.0 (Compatible) [Functional] 
System: Windows
GPU not recognized by LM Studio (it was working before) 
My GPU is an Intel Arc A770 16GB (Intel's AI Playground is still working from the GPU so I don't know what went wrong after the LM studio Vulkan llama.cpp runtime update) 
Mission control > Hardware > 0 GPUs detected & 0 VRAM 
LM Studio still works while running via RAM + CPU (but slowly)

Everything was working fine before with the Arc A770 GPU. Im not sure if it was the LM Studio update or if it was the Vulkan llama.cpp update. 
Forgive me if this is presented in an improper format, I have no software/coding/programming experience and this is my first bug report. 

Logs attached

[LM Studio App Log.txt](https://github.com/user-attachments/files/18622667/LM.Studio.App.Log.txt)

**Comment by yagil** [comment]
This might be fixed in 0.3.9 **b6**, available on https://lmstudio.ai/download. If you try it, please let us know if it worked

**Comment by Slurpeeguy** [comment]
Thank you so much for your reply but unfortunately this did not fix the issue.

________________________________

**Comment by ywnsya** [comment]
I experienced the same problem when I updated the A770 driver to 101.6557, and it was resolved when I rolled back to 101.6460, so I believe this is a driver issue that can be temporarily fixed by rolling back the driver version to 101.6460

**Comment by zhiqiuhu** [comment]
The issue for me is that lm_studio can no longer detect any GPU since 0.3.9 (Build 5) [0 GPU].

My setting is Windows 11 Pro: Intel(R) Arc(TM) A770M Graphics (discrete) + Intel(R) Iris(R) Xe (integrated) Graphics - Driver Version: 32.0.101.6460. 

Previously (build 4 and before), it can detect Intel(R) Arc(TM) A770M Graphics with no issue. 


Updates: My issue was resolved after starting lm_studio as admin. Remember this was not previously necessary.

**Comment by Slurpeeguy** [comment]
> The issue for me is that lm_studio can no longer detect any GPU since 0.3.9 (Build 5) [0 GPU].
> 
> My setting is Windows 11 Pro: Intel(R) Arc(TM) A770M Graphics (discrete) + Intel(R) Iris(R) Xe (integrated) Graphics - Driver Version: 32.0.101.6460.
> 
> Previously (build 4 and before), it can detect Intel(R) Arc(TM) A770M Graphics with no issue.
> 
> Updates: My issue was resolved after starting lm_studio as admin. Remember this was not previously necessary.

It also resolved for me when I started LM Studio as an Admin

**Comment by IronFenyx** [comment]
Confirm. I ran LM Studio 0.39-3 (Windows 11) in the usual way and the program did not see the intel arc a580 graphics card. After reading this topic, I downloaded the updated version 0.39-6 and launched it with administrator rights. Also, inside the program, I updated llama.cpp up to the latest version. By that time, I had three versions of this library. All of them were marked as available for use and my graphics card appeared in the list of video adapters! It works through the Vulkan!

**Comment by Slurpeeguy** [comment]
**UPDATE**

Version 0.3.10 (Build 4) completely fixed all issues I had reported. 

Thank you devs.

**Comment by alucard1792** [comment]
Yes, if you run lm studio with admin privileges, my intel arc a770 is recognized in the hardware section:

![Image](https://github.com/user-attachments/assets/416faccb-cf5f-4da7-8350-7b57251629d0)

**Comment by vikrantSinghOnGithub** [comment]
Apart this issue, Can you share token/sec while running the model with llama.cpp and vulkan

**Comment by Slurpeeguy** [comment]
> Apart this issue, Can you share token/sec while running the model with llama.cpp and vulkan

I'm currently using 2 models for experimentation.
Intel Arc A770 - 16GB VRAM 
Deepseek R1 Qwen 7B (Q8) - 29.35 tokens per second (Vulkan)
Microsoft phi 3.5 3B (Q8) - 48.32 tokens per second (Vulkan)

**Comment by Nakagawa-Nagi** [comment]
> **UPDATE**
> 
> Version 0.3.10 (Build 4) completely fixed all issues I had reported.
> 
> Thank you devs.

hello！
i use the same gpu as yours, and my LMS recognized it successfully, but when i tried to load a model, it always didn't work like this.

<img width="1029" height="238" alt="Image" src="https://github.com/user-attachments/assets/530b4bc1-553e-4466-a698-b5fa89651384" />

<img width="503" height="205" alt="Image" src="https://github.com/user-attachments/assets/9097c46e-0764-4df1-89d8-7b7781e700e1" />

whichever model is the same problem, from small(1B) to large(70B). My drivers have update to the latest and all the runtime apps have been updated to the lateest version. But it still cant run. All the models  can run rightly while using cpu.

btw, i tried to run stable diffusion and it worked very well

<img width="1539" height="726" alt="Image" src="https://github.com/user-attachments/assets/52e8f9f1-fbcb-4b8f-88cf-7ce9275a2c52" />
this problem had puzzled me quite a lot time, hope you could have some idea, plz

**Comment by Nakagawa-Nagi** [comment]
when running stable diffusion:
<img width="763" height="674" alt="Image" src="https://github.com/user-attachments/assets/2094c11f-c846-42f8-8852-8e0417caeb72" />

**Comment by Slurpeeguy** [comment]
Sorry, not sure how to help you. I don’t really know much about software. I do this as a hobby. I hope the devs see this and help you. Upload your logs here if you can.

Have you tried running LMS as an administrator?

**Comment by ObscurusMortuus** [comment]
I downgraded version of Vulkan in LM Studio - It worked for me. Models loading, no errors

**Comment by mrobbeloth** [comment]
Vulcan Version 1.63.1 seems to work fine as an Engine, but 1.102.0 does not. I am using an Intel Arc on an Ultra 7 155H
