### ISSUE TITLE
CUDA backend error loading model on cards with CUDA compute capability 5.x

### ISSUE THREAD

**Issue by puff-dayo** [lmstudio-ai/lmstudio-bug-tracker#414]
LMStudio 0.3.9 build 6 (CUDA backend 1.11.0) on Windows10 with GTX980M. Literally any model with CUDA:

Error msg on UI:

```
Failed to load last used model.

Error loading model.

(Exit code: 18446744072635812000). Unknown error. Try a different model and/or config.
```

Checking verbose log through dev window:

```
....

2025-02-02 00:23:21 [DEBUG] 
common_init_from_params: setting dry_penalty_last_n to ctx_size = 4096
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
2025-02-02 00:23:21 [DEBUG] 
ggml_cuda_compute_forward: RMS_NORM failed
2025-02-02 00:23:21 [DEBUG] 
CUDA error: no kernel image is available for execution on the device
  current device: 0, in function ggml_cuda_compute_forward at C:\a\llmster\llmster\electron\vendor\llm-engine\llama.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:2311
  err
llama.cpp abort:72: CUDA error
```

I'm guessing that `CUDA error: no kernel image is available for execution on the device` is related to not including some fields for some cards with CUDA capability as 5.x?

Selecting a CPU/Vulkan runtime instead of CUDA fixes the situation but that significantly impact performance, though.

Possible similar issue: https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/297 https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/165

**Comment by wukongzhikong** [comment]
Same problem. It should be related to cuda llama.cpp backend compile flag.

**Comment by puff-dayo** [comment]
More similar issues: https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/432, https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/424

I'd say very nice UI, but it would be nice to be able to load models. 

The Vulkan backend would have a serious performance and functionality loss compared to the CUDA backend.

And a bunch of the old era top cards like GTX980 and Titans don't have a worse model inference experience in real world testing than the newer xx50s and xx60s, it's sad to see that they're being dropped from support.

**Comment by yagil** [comment]
Is it the case the it used to work and now doesn't, or did it simply never work?

**Comment by puff-dayo** [comment]
Thanks for your investigation and efforts. It simply never work in LMStudio (CUDA backend).

I tested with cudart-llama-bin-win-cu12.4-x64 inside the b4724 release of llama.cpp and the model loads and inference on GPU is fine.

**Comment by puff-dayo** [comment]
I just found a fix for this issue:

**Download** a cudart-llama-bin-win-cu12.4-x64 and llama.cpp-cuda binary release, **unzip and copy** these four dlls into LMStudio's runtime folder.

And it works. Super fast. CUDA backend is like a 2x~3x speed boost than Vulkan.

```
"C:\Users\User\.lmstudio\extensions\backends\llama.cpp-win-x86_64-nvidia-cuda-avx2-1.15.3\cublas64_12.dll" - New
"C:\Users\User\.lmstudio\extensions\backends\llama.cpp-win-x86_64-nvidia-cuda-avx2-1.15.3\cublasLt64_12.dll" - New
"C:\Users\User\.lmstudio\extensions\backends\llama.cpp-win-x86_64-nvidia-cuda-avx2-1.15.3\cudart64_12.dll" - New
"C:\Users\User\.lmstudio\extensions\backends\llama.cpp-win-x86_64-nvidia-cuda-avx2-1.15.3\ggml-cuda.dll" - Replace
```

**Comment by yagil** [comment]
@puff-dayo we have a few questions that will help us discover the root cause. Are you able to email us at `bugs@lmstudio.ai` to start the conversation? Thank you!

**Comment by mattjcly** [comment]
Hi @puff-dayo @wukongzhikong and others. 

We've just uploaded a new beta runtime that should hopefully fix this problem

Could you try the new v.1.16.0 runtime and let us know if it fixes? (Without the need for modification)

![Image](https://github.com/user-attachments/assets/d5615aa6-2485-43e6-9949-14ff9e851381)
Ctrl+Shift+R to get to this page (I am on mac at the moment so it says incompatible, but should be compatible for you)

**Comment by puff-dayo** [comment]
Thanks for your efforts! Updated to the new's v.1.16.0 runtime CUDA backend and everything is working fine and very fast.
Thanks again!

**Comment by PureJourney** [comment]
@mattjcly only added support for compute capability 5.2? why not add 5.0 as well? i got a 5.0 card, which is supported by cuda afaik.

**Comment by wukongzhikong** [comment]
thank you for the update, however, it‘s not working for my gtx 960m with cuda 5.0  compute capability.

> Hi [@puff-dayo](https://github.com/puff-dayo) [@wukongzhikong](https://github.com/wukongzhikong) and others.
> 
> We've just uploaded a new beta runtime that should hopefully fix this problem
> 
> Could you try the new v.1.16.0 runtime and let us know if it fixes? (Without the need for modification)
> 
> ![Image](https://github.com/user-attachments/assets/d5615aa6-2485-43e6-9949-14ff9e851381) Ctrl+Shift+R to get to this page (I am on mac at the moment so it says incompatible, but should be compatible for you)

**Comment by neilmehta24** [comment]
@PureJourney @wukongzhikong we released llama.cpp runtime v1.16.1 which provides support for compute capability 5.0. You can download it from the runtimes beta channel. This should resolve your issue. Thank you for bringing this to our attention

**Comment by PureJourney** [comment]
@neilmehta24  Yet v1.16.1 haven't shown up in the runtimes beta channel. Is it a problem on my side?

**Comment by neilmehta24** [comment]
@PureJourney I forgot to mark it as beta on my end, sorry! It should be available now, please refresh!

**Comment by PureJourney** [comment]
@neilmehta24 downloaded and tested. worked like a charm. you are the man.

**Comment by wukongzhikong** [comment]
> [@PureJourney](https://github.com/PureJourney) [@wukongzhikong](https://github.com/wukongzhikong) we released llama.cpp runtime v1.16.1 which provides support for compute capability 5.0. You can download it from the runtimes beta channel. This should resolve your issue. Thank you for bringing this to our attention

works perfectly! thank you for your update!

**Comment by ref202404** [comment]
> [@PureJourney](https://github.com/PureJourney) [@wukongzhikong](https://github.com/wukongzhikong) we released llama.cpp runtime v1.16.1 which provides support for compute capability 5.0. You can download it from the runtimes beta channel. This should resolve your issue. Thank you for bringing this to our attention

Hi, just tested on my 2080TI/22G. The latest working CUDA llama.cpp runtime version is v1.15.3.  Both v1.17.1 and v1.16.1 will lead to (Exit code: 18446744072635812000). Unknown error. when loading models.

**Comment by neilmehta24** [comment]
Hello @ref202404 , this sounds like a different bug. Are you still seeing this issue on the latest build of LM Studio, 0.3.10? If you are, could you please download [this debug build](https://files.lmstudio.ai/windows/super-debug/1/LM-Studio-0.3.10-6-alpha-win32-x64.exe) and send us the logs when using `v1.16.1`. We would need the app logs, and the verbose logs from the server page.

I opened up this new issue https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/471 since what you're seeing is likely unrelated to the previous discussion, please respond back in the new issue

**Comment by tienomeis** [comment]
I do have an Nvidia card with CUDA compute capability 3.0
Any chance to get CUDA running on this card?
